In [38]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import itertools
import csv

In [61]:
files = ['C:/Users/Elite/رفع الى GitHub/Restaurant.csv'] # polarity,text,restaurant_id,user_id

In [62]:
def prepareDatasets(files):
    sentences = []

    for file_name in files:
        file = open(file_name, "rt", encoding="utf-8-sig")
        reviews = csv.reader(file)
        
        next(reviews, None)   # لتجاوز أول صف header
        
        for polarity, text, restaurant_id, user_id in reviews:
            sentences.append([text, polarity])

        file.close()

    df = DataFrame(sentences, columns=['text', 'polarity'])
    return df

In [65]:
reviews = prepareDatasets(files)

In [66]:
reviews

                                                 text polarity
0   اولا: المنيو تغير والشاورما أصبحت عادية للأسف ...       -1
1   من أفضل محلات الشاورما، الصلصات ممتازة والطعم ...        1
2      دجاج طازج يحضر أمامك على الطلب والنظافة واضحة.        1
3        المكان جميل والجلسات مريحة والأكل لذيذ جدًا.        1
4   دعاية المطعم أكبر من مستواه الحقيقي، الأسعار م...       -1
5                    انتظرت كثيرًا والطلب وصل باردًا.       -1
6                      الفلافل والحمص عندهم ولا أروع.        1
7        جربت المحشي ولم يعجبني وكان غير مستوي جيدًا.       -1
8             المطعم رائع والأكل نظيف والخدمة محترمة.        1
9           لا يوجد تنظيم عند المحاسب والطلبات تتأخر.       -1
10               المشويات ممتازة والرز البرياني لذيذ.        1
11                      فطور رائع جدًا وأنصح بتجربته.        1
12                   للأسف النظافة سيئة في هذا الفرع.       -1
13        الأسعار مناسبة والطعم ممتاز بالنسبة للبرجر.        1
14                   أجواء جميلة ومكان مناسب للعائلة.        1
15         المطعم مغلق منذ فترة ولا توجد خدمة حاليًا.       -1
16                   بصراحة الطعم خيال والخدمة سريعة.        1
17                    الكباب والنقانق كانت جيدة جدًا.        1
18              شوربة وتقاطيع مقبولة لكن ليست الأفضل.       -1
19     المطعم من أفضل المطاعم في المنطقة والطعم ثابت.        1

In [74]:
def getData():
    df = pd.read_csv('C:/Users/Elite/رفع الى GitHub/Restaurant.csv', encoding='utf-8-sig')
    reviews = df[['text', 'polarity']]
    return reviews

In [75]:
reviews = getData()
reviews.head()

                                                text  polarity
0  اولا: المنيو تغير والشاورما أصبحت عادية للأسف ...        -1
1  من أفضل محلات الشاورما، الصلصات ممتازة والطعم ...         1
2     دجاج طازج يحضر أمامك على الطلب والنظافة واضحة.         1
3       المكان جميل والجلسات مريحة والأكل لذيذ جدًا.         1
4  دعاية المطعم أكبر من مستواه الحقيقي، الأسعار م...        -1

In [82]:
for text, polarity in zip(reviews['text'], reviews['polarity']):
    print(text, polarity)

اولا: المنيو تغير والشاورما أصبحت عادية للأسف والخدمة بطيئة. -1
من أفضل محلات الشاورما، الصلصات ممتازة والطعم رائع. 1
دجاج طازج يحضر أمامك على الطلب والنظافة واضحة. 1
المكان جميل والجلسات مريحة والأكل لذيذ جدًا. 1
دعاية المطعم أكبر من مستواه الحقيقي، الأسعار مرتفعة. -1
انتظرت كثيرًا والطلب وصل باردًا. -1
الفلافل والحمص عندهم ولا أروع. 1
جربت المحشي ولم يعجبني وكان غير مستوي جيدًا. -1
المطعم رائع والأكل نظيف والخدمة محترمة. 1
لا يوجد تنظيم عند المحاسب والطلبات تتأخر. -1
المشويات ممتازة والرز البرياني لذيذ. 1
فطور رائع جدًا وأنصح بتجربته. 1
للأسف النظافة سيئة في هذا الفرع. -1
الأسعار مناسبة والطعم ممتاز بالنسبة للبرجر. 1
أجواء جميلة ومكان مناسب للعائلة. 1
المطعم مغلق منذ فترة ولا توجد خدمة حاليًا. -1
بصراحة الطعم خيال والخدمة سريعة. 1
الكباب والنقانق كانت جيدة جدًا. 1
شوربة وتقاطيع مقبولة لكن ليست الأفضل. -1
المطعم من أفضل المطاعم في المنطقة والطعم ثابت. 1

In [86]:
files = ['C:/Users/Elite/رفع الى GitHub/Restaurant.csv']

In [87]:
def modifyCSV(files):
    for file in files:
        df = pd.read_csv(file)
        del df['user_id']
        del df['restaurant_id']
        
        df.to_csv('new_csv_h_res.csv')
        return df

In [88]:
reviews = modifyCSV(files)

In [89]:
reviews

    polarity                                               text
0         -1  اولا: المنيو تغير والشاورما أصبحت عادية للأسف ...
1          1  من أفضل محلات الشاورما، الصلصات ممتازة والطعم ...
2          1     دجاج طازج يحضر أمامك على الطلب والنظافة واضحة.
3          1       المكان جميل والجلسات مريحة والأكل لذيذ جدًا.
4         -1  دعاية المطعم أكبر من مستواه الحقيقي، الأسعار م...
5         -1                   انتظرت كثيرًا والطلب وصل باردًا.
6          1                     الفلافل والحمص عندهم ولا أروع.
7         -1       جربت المحشي ولم يعجبني وكان غير مستوي جيدًا.
8          1            المطعم رائع والأكل نظيف والخدمة محترمة.
9         -1          لا يوجد تنظيم عند المحاسب والطلبات تتأخر.
10         1               المشويات ممتازة والرز البرياني لذيذ.
11         1                      فطور رائع جدًا وأنصح بتجربته.
12        -1                   للأسف النظافة سيئة في هذا الفرع.
13         1        الأسعار مناسبة والطعم ممتاز بالنسبة للبرجر.
14         1                   أجواء جميلة ومكان مناسب للعائلة.
15        -1         المطعم مغلق منذ فترة ولا توجد خدمة حاليًا.
16         1                   بصراحة الطعم خيال والخدمة سريعة.
17         1                    الكباب والنقانق كانت جيدة جدًا.
18        -1              شوربة وتقاطيع مقبولة لكن ليست الأفضل.
19         1     المطعم من أفضل المطاعم في المنطقة والطعم ثابت.